### ISSUE TITLE
Error when swipe down

### ISSUE THREAD

**Issue by kalvish21** [soarcn/BottomSheet#75]
When I swipe down with this menu I get the following error:

`Attempting to destroy the window while drawing!`

When I try to click on my Button to show the dialog again it doesn't show, the screen simply flashes black for a split second. When I click on the Button again it shows properly. The only way I was able to get this to work is by doing this for canceling:

`closeOptionsMenu()` and `sheet.setCanceledOnSwipeDown(false);`

Is there a way to get the swipe down working properly?

**Comment by soarcn** [comment]
I'll soon update a patch for this.

**Comment by kalvish21** [comment]
I actually have it fixed locally.

If you goto `ClosableSlidingLayout` and change the following:

            case MotionEvent.ACTION_DOWN:
                height = getChildAt(0).getHeight();
                top = getChildAt(0).getTop();

to the below:

            case MotionEvent.ACTION_DOWN:
                height = getHeight();
                top = getTop();

It fixed it on my end! I can provide a pull request if needed.

**Comment by kalvish21** [comment]
It seems the height was being calculated incorrectly.

**Comment by harishrpatel** [comment]
Hey Kai, We love BottomSheet. It would be nice if you can fix this issue. Since the sheet animates nicely from bottom, some users would be tempted to swipe down. So, this fix would really help.

**Comment by soarcn** [comment]
@harishrpatel  is there any easy way to reproduce this defect?

**Comment by harishrpatel** [comment]
Yes, happens everytime. Simply show BottomSheet and then swipe down to close it. It closes, but next time I click on my action button, it does not show up. If you click one more time, then it shows up. I believe that kalvish21 on this thread has suggested fix. Thanks for quick response.

**Comment by soarcn** [comment]
I will fix this asap

**Comment by kalvish21** [comment]
I actually posted my solution above; works perfectly when I do it. Feel free to use that or improve on it and come up with a better one!

**Comment by kalvish21** [comment]
The height is not being calculated properly, so when dragging down its trying to release the object from memory but it is still being shown and then an exception is thrown.

**Comment by soarcn** [comment]
@kalvish21 Good job, I will verify it again. thanks!

**Comment by soarcn** [comment]
I pushed the fix to master branch. @kalvish21 's patch is working for most of cases, but there is a problem when user swiping up to expand in full-screen mode. I'll do further test before updating to maven repository.

**Comment by kalvish21** [comment]
I'm still getting a weirdness in the fix. It pauses slightly when sliding down. Remember I said about height being calculated incorrectly and it's trying to release the object? I'm pretty sure thats what's happening.

**Comment by gnuhel** [comment]
will this issue be fixed?

**Comment by soarcn** [comment]
@gnuhel The original error has been fixed with the side effect it will pause slightly when sliding down.

further development plan, please check #111
